#!/bin/bash
# ============================================================
# UAVLogBook — Automated Server Installer
# Run via SSH on your cPanel hosting:
#   bash install_server.sh
# ============================================================
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo -e "${BLUE}╔══════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   UAVLogBook Server Installer v1.0   ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Check PHP ─────────────────────────────────────────────────
info "Checking PHP version..."
PHP_VER=$(php -r 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION;' 2>/dev/null || echo "0")
if (( $(echo "$PHP_VER < 7.4" | bc -l) )); then
    error "PHP 7.4+ required. Found: $PHP_VER"
fi
success "PHP $PHP_VER found"

# ── Check extensions ──────────────────────────────────────────
for ext in pdo pdo_mysql json curl mbstring; do
    if php -m | grep -qi "$ext"; then
        success "PHP extension $ext: OK"
    else
        warn "PHP extension $ext: MISSING (may cause errors)"
    fi
done

# ── Prompt for config ─────────────────────────────────────────
echo ""
echo -e "${YELLOW}=== Database Configuration ===${NC}"
read -p "MySQL Host [localhost]: " DB_HOST; DB_HOST=${DB_HOST:-localhost}
read -p "MySQL Database name: " DB_NAME
read -p "MySQL Username: " DB_USER
read -s -p "MySQL Password: " DB_PASS; echo ""
read -p "Public domain (e.g. https://yourdomain.com): " DOMAIN

echo ""
echo -e "${YELLOW}=== AI Configuration (optional) ===${NC}"
read -p "Anthropic API Key (leave blank to skip AI features): " AI_KEY

# ── Detect document root ──────────────────────────────────────
if [ -d "$HOME/public_html" ]; then
    WEB_ROOT="$HOME/public_html"
elif [ -d "/var/www/html" ]; then
    WEB_ROOT="/var/www/html"
else
    read -p "Enter your web root path: " WEB_ROOT
fi
info "Web root: $WEB_ROOT"

# ── Create directory structure ────────────────────────────────
info "Creating directory structure..."
mkdir -p "$WEB_ROOT/api"
mkdir -p "$WEB_ROOT/../uavlogbook_data/uploads/logs"
mkdir -p "$WEB_ROOT/../uavlogbook_data/config"

UPLOAD_DIR="$HOME/uavlogbook_data/uploads/logs/"
VIDEO_DIR="$HOME/uavlogbook_data/uploads/videos/"
mkdir -p "$UPLOAD_DIR"
mkdir -p "$VIDEO_DIR"
chmod 755 "$UPLOAD_DIR"
chmod 755 "$VIDEO_DIR"

# ── Copy server files ─────────────────────────────────────────
info "Copying server files..."
cp -r server/config  "$WEB_ROOT/api/"
cp -r server/middleware "$WEB_ROOT/api/"
cp -r server/parsers "$WEB_ROOT/api/"
cp -r server/ai      "$WEB_ROOT/api/"
cp    server/api/index.php    "$WEB_ROOT/api/"
cp    server/api/processor.php "$WEB_ROOT/api/"
cp    server/.htaccess "$WEB_ROOT/.htaccess"

# ── Write config ──────────────────────────────────────────────
info "Writing configuration..."
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 64)

cat > "$WEB_ROOT/api/config/config.local.php" <<EOF
<?php
// UAVLogBook — Local Configuration (auto-generated by installer)
// DO NOT commit this file to version control

define('DB_HOST',     '$DB_HOST');
define('DB_NAME',     '$DB_NAME');
define('DB_USER',     '$DB_USER');
define('DB_PASS',     '$DB_PASS');
define('DB_CHARSET',  'utf8mb4');
define('JWT_SECRET',  '$JWT_SECRET');
define('JWT_EXPIRY_HOURS', 72);
define('UPLOAD_DIR',  '$UPLOAD_DIR');
define('VIDEO_UPLOAD_DIR', '$VIDEO_DIR');
define('VIDEO_WEB_PATH',   '/uploads/videos/');
define('MAX_FILE_MB', 500);
define('ANTHROPIC_API_KEY', '$AI_KEY');
define('AI_MODEL',    'claude-sonnet-4-20250514');
define('TELEM_MAX_POINTS', 5000);
define('ALLOWED_ORIGINS', ['$DOMAIN', 'http://localhost:3000', 'http://localhost:19006']);
define('APP_VERSION', '1.0.0');
define('API_VERSION', 'v1');
EOF

# Update config.php to load local config if it exists
cat > "$WEB_ROOT/api/config/config.php" <<'PHPEOF'
<?php
$localCfg = __DIR__ . '/config.local.php';
if (file_exists($localCfg)) {
    require_once $localCfg;
} else {
    // Fallback to environment variables
    define('DB_HOST',     getenv('UAVLOG_DB_HOST')     ?: 'localhost');
    define('DB_NAME',     getenv('UAVLOG_DB_NAME')     ?: 'uavlogbook');
    define('DB_USER',     getenv('UAVLOG_DB_USER')     ?: 'uavlogbook_user');
    define('DB_PASS',     getenv('UAVLOG_DB_PASS')     ?: '');
    define('DB_CHARSET',  'utf8mb4');
    define('JWT_SECRET',  getenv('UAVLOG_JWT_SECRET')  ?: 'changeme');
    define('JWT_EXPIRY_HOURS', 72);
    define('UPLOAD_DIR',  dirname(dirname(__DIR__)) . '/uploads/logs/');
    define('MAX_FILE_MB', 500);
    define('ANTHROPIC_API_KEY', getenv('ANTHROPIC_API_KEY') ?: '');
    define('AI_MODEL',    'claude-sonnet-4-20250514');
    define('TELEM_MAX_POINTS', 5000);
    define('ALLOWED_ORIGINS', []);
    define('APP_VERSION', '1.0.0');
    define('API_VERSION', 'v1');
}
PHPEOF

# ── Run database schema ───────────────────────────────────────
info "Creating database tables..."
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < server/db/schema.sql && \
    success "Database schema installed" || \
    warn "Could not run schema automatically. Please import server/db/schema.sql via phpMyAdmin"

# ── Deploy web app ────────────────────────────────────────────
if [ -d "web/dist" ]; then
    info "Deploying web app..."
    cp -r web/dist/* "$WEB_ROOT/"
    success "Web app deployed to $WEB_ROOT"
else
    warn "Web app not built yet. Run: cd web && npm install && npm run build"
    warn "Then copy web/dist/* to $WEB_ROOT/"
fi

# ── Set permissions ───────────────────────────────────────────
info "Setting permissions..."
find "$WEB_ROOT" -type f -name "*.php" -exec chmod 644 {} \;
find "$WEB_ROOT" -type d -exec chmod 755 {} \;
chmod 600 "$WEB_ROOT/api/config/config.local.php"
chmod 755 "$UPLOAD_DIR"

# ── Test API ──────────────────────────────────────────────────
info "Testing API..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$DOMAIN/api/v1/auth/login" -X POST \
    -H "Content-Type: application/json" -d '{"email":"test","password":"test"}' 2>/dev/null || echo "000")

if [ "$HTTP_CODE" = "401" ]; then
    success "API is responding correctly (401 = auth working)"
elif [ "$HTTP_CODE" = "000" ]; then
    warn "Could not reach API — check your domain and SSL"
else
    warn "API returned HTTP $HTTP_CODE — check error logs"
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Installation Complete!            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""
echo -e "  API URL:   ${BLUE}$DOMAIN/api/v1${NC}"
echo -e "  Web App:   ${BLUE}$DOMAIN${NC}"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "  1. Open $DOMAIN in your browser"
echo -e "  2. Register your first account"
echo -e "  3. Build the mobile app (see INSTALL.pdf)"
echo ""
